// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { ExecuteRecentBlocksRecentBlocksPostData, ExecuteRecentBlocksRecentBlocksPostResponses, GetActivitiesMeterMeterIdActivitiesGetData, GetActivitiesMeterMeterIdActivitiesGetErrors, GetActivitiesMeterMeterIdActivitiesGetResponses, GetDailyBatchDailyBatchGetData, GetDailyBatchDailyBatchGetErrors, GetDailyBatchDailyBatchGetResponses, GetDailyMeterMeterIdDailyGetData, GetDailyMeterMeterIdDailyGetErrors, GetDailyMeterMeterIdDailyGetResponses, GetMonthOfYearMeterMeterIdMonthMonthYearGetData, GetMonthOfYearMeterMeterIdMonthMonthYearGetErrors, GetMonthOfYearMeterMeterIdMonthMonthYearGetResponses, GetProposalProposalTxHashGetData, GetProposalProposalTxHashGetErrors, GetProposalProposalTxHashGetResponses, GetRecentBlocksRecentBlocksGetData, GetRecentBlocksRecentBlocksGetResponses, GetWeeklyMeterMeterIdWeeklyGetData, GetWeeklyMeterMeterIdWeeklyGetErrors, GetWeeklyMeterMeterIdWeeklyGetResponses, GetWeeksOfYearMeterMeterIdWeeksYearGetData, GetWeeksOfYearMeterMeterIdWeeksYearGetErrors, GetWeeksOfYearMeterMeterIdWeeksYearGetResponses, GetWorldStateWorldStateGetData, GetWorldStateWorldStateGetResponses, ReadRootGetData, ReadRootGetResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Read Root
 *
 * Welcome message to our users.
 */
export const readRootGet = <ThrowOnError extends boolean = false>(options?: Options<ReadRootGetData, ThrowOnError>): RequestResult<ReadRootGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({ url: '/', ...options });

/**
 * Get Recent Blocks
 *
 * Get latest blocks
 */
export const getRecentBlocksRecentBlocksGet = <ThrowOnError extends boolean = false>(options?: Options<GetRecentBlocksRecentBlocksGetData, ThrowOnError>): RequestResult<GetRecentBlocksRecentBlocksGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetRecentBlocksRecentBlocksGetResponses, unknown, ThrowOnError>({ url: '/recent-blocks', ...options });

/**
 * Execute Recent Blocks
 *
 * Execute query for recent blocks on dune
 */
export const executeRecentBlocksRecentBlocksPost = <ThrowOnError extends boolean = false>(options?: Options<ExecuteRecentBlocksRecentBlocksPostData, ThrowOnError>): RequestResult<ExecuteRecentBlocksRecentBlocksPostResponses, unknown, ThrowOnError> => (options?.client ?? client).post<ExecuteRecentBlocksRecentBlocksPostResponses, unknown, ThrowOnError>({ url: '/recent-blocks', ...options });

/**
 * Get World State
 *
 * Lorem ipsum
 */
export const getWorldStateWorldStateGet = <ThrowOnError extends boolean = false>(options?: Options<GetWorldStateWorldStateGetData, ThrowOnError>): RequestResult<GetWorldStateWorldStateGetResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetWorldStateWorldStateGetResponses, unknown, ThrowOnError>({ url: '/world-state', ...options });

/**
 * Get Daily Batch
 *
 * Get daily Batch
 */
export const getDailyBatchDailyBatchGet = <ThrowOnError extends boolean = false>(options: Options<GetDailyBatchDailyBatchGetData, ThrowOnError>): RequestResult<GetDailyBatchDailyBatchGetResponses, GetDailyBatchDailyBatchGetErrors, ThrowOnError> => (options.client ?? client).get<GetDailyBatchDailyBatchGetResponses, GetDailyBatchDailyBatchGetErrors, ThrowOnError>({ url: '/daily-batch', ...options });

/**
 * Get Daily
 *
 * Get daily energy usage aggregate.
 */
export const getDailyMeterMeterIdDailyGet = <ThrowOnError extends boolean = false>(options: Options<GetDailyMeterMeterIdDailyGetData, ThrowOnError>): RequestResult<GetDailyMeterMeterIdDailyGetResponses, GetDailyMeterMeterIdDailyGetErrors, ThrowOnError> => (options.client ?? client).get<GetDailyMeterMeterIdDailyGetResponses, GetDailyMeterMeterIdDailyGetErrors, ThrowOnError>({ url: '/meter/{meter_id}/daily', ...options });

/**
 * Get Weekly
 *
 * Get weekly energy usage aggregate.
 */
export const getWeeklyMeterMeterIdWeeklyGet = <ThrowOnError extends boolean = false>(options: Options<GetWeeklyMeterMeterIdWeeklyGetData, ThrowOnError>): RequestResult<GetWeeklyMeterMeterIdWeeklyGetResponses, GetWeeklyMeterMeterIdWeeklyGetErrors, ThrowOnError> => (options.client ?? client).get<GetWeeklyMeterMeterIdWeeklyGetResponses, GetWeeklyMeterMeterIdWeeklyGetErrors, ThrowOnError>({ url: '/meter/{meter_id}/weekly', ...options });

/**
 * Get Weeks Of Year
 *
 * Get energy usage of all weeks of specified year.
 */
export const getWeeksOfYearMeterMeterIdWeeksYearGet = <ThrowOnError extends boolean = false>(options: Options<GetWeeksOfYearMeterMeterIdWeeksYearGetData, ThrowOnError>): RequestResult<GetWeeksOfYearMeterMeterIdWeeksYearGetResponses, GetWeeksOfYearMeterMeterIdWeeksYearGetErrors, ThrowOnError> => (options.client ?? client).get<GetWeeksOfYearMeterMeterIdWeeksYearGetResponses, GetWeeksOfYearMeterMeterIdWeeksYearGetErrors, ThrowOnError>({ url: '/meter/{meter_id}/weeks/{year}', ...options });

/**
 * Get Month Of Year
 *
 * Get daily energy usage for a given month in a specified year.
 */
export const getMonthOfYearMeterMeterIdMonthMonthYearGet = <ThrowOnError extends boolean = false>(options: Options<GetMonthOfYearMeterMeterIdMonthMonthYearGetData, ThrowOnError>): RequestResult<GetMonthOfYearMeterMeterIdMonthMonthYearGetResponses, GetMonthOfYearMeterMeterIdMonthMonthYearGetErrors, ThrowOnError> => (options.client ?? client).get<GetMonthOfYearMeterMeterIdMonthMonthYearGetResponses, GetMonthOfYearMeterMeterIdMonthMonthYearGetErrors, ThrowOnError>({ url: '/meter/{meter_id}/month/{month}/{year}', ...options });

/**
 * Get Activities
 *
 * Get activities of a m3ter
 *
 * :param m3ter_id: Description
 * :type m3ter_id: int
 */
export const getActivitiesMeterMeterIdActivitiesGet = <ThrowOnError extends boolean = false>(options: Options<GetActivitiesMeterMeterIdActivitiesGetData, ThrowOnError>): RequestResult<GetActivitiesMeterMeterIdActivitiesGetResponses, GetActivitiesMeterMeterIdActivitiesGetErrors, ThrowOnError> => (options.client ?? client).get<GetActivitiesMeterMeterIdActivitiesGetResponses, GetActivitiesMeterMeterIdActivitiesGetErrors, ThrowOnError>({ url: '/meter/{meter_id}/activities', ...options });

/**
 * Get Proposal
 *
 * Retrieve proposal details by transaction hash.
 *
 * First checks the database cache. If not found, fetches from Ethereum
 * blockchain, decodes the transaction data, and caches the results.
 *
 * :param tx_hash: Ethereum transaction hash
 * :type tx_hash: str
 * :return: List of proposal meter readings
 */
export const getProposalProposalTxHashGet = <ThrowOnError extends boolean = false>(options: Options<GetProposalProposalTxHashGetData, ThrowOnError>): RequestResult<GetProposalProposalTxHashGetResponses, GetProposalProposalTxHashGetErrors, ThrowOnError> => (options.client ?? client).get<GetProposalProposalTxHashGetResponses, GetProposalProposalTxHashGetErrors, ThrowOnError>({ url: '/proposal/{tx_hash}', ...options });
