// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'https://m3terscan-api.onrender.com' | (string & {});
};

/**
 * Activities
 *
 * Docstring for Activities
 */
export type Activities = {
    /**
     * Timestamp
     */
    timestamp: number;
    /**
     * Energy
     */
    energy: number;
    /**
     * Signature
     */
    signature: string;
};

/**
 * ActivitiesResponse
 *
 * Docstring for ActivitiesResponse
 */
export type ActivitiesResponse = {
    /**
     * Data
     */
    data: Array<Activities>;
    /**
     * Limit
     */
    limit: number;
    /**
     * Next Cursor
     */
    next_cursor: string;
};

/**
 * DailyResponse
 *
 * Response model for daily enpoint.
 */
export type DailyResponse = {
    /**
     * Hour Start Utc
     */
    hour_start_utc: string;
    /**
     * Total Energy
     */
    total_energy: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * MonthlyEnergyRead
 */
export type MonthlyEnergyRead = {
    /**
     * Day
     */
    day: number;
    /**
     * Month
     */
    month: number;
    /**
     * Year
     */
    year: number;
    /**
     * Meter Id
     */
    meter_id: number;
    /**
     * Total Energy
     */
    total_energy: number;
};

/**
 * ProposalsResponse
 *
 * Represents the structured response containing a meter number,
 * a formatted account ID, and a nonce value.
 */
export type ProposalsResponse = {
    /**
     * M3Ter No
     */
    m3ter_no: number;
    /**
     * Account
     */
    account: string;
    /**
     * Nonce
     */
    nonce: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

/**
 * WeeklyResponse
 *
 * Response model for weekly enpoint.
 */
export type WeeklyResponse = {
    /**
     * Day Of Week
     */
    day_of_week: number;
    /**
     * Total Energy
     */
    total_energy: number;
};

/**
 * WeeksEnergyRead
 */
export type WeeksEnergyRead = {
    /**
     * Year
     */
    year: number;
    /**
     * Week
     */
    week: number;
    /**
     * Meter Id
     */
    meter_id: number;
    /**
     * Total Energy
     */
    total_energy: number;
};

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetRecentBlocksRecentBlocksGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/recent-blocks';
};

export type GetRecentBlocksRecentBlocksGetResponses = {
    /**
     * Response Get Recent Blocks Recent Blocks Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetRecentBlocksRecentBlocksGetResponse = GetRecentBlocksRecentBlocksGetResponses[keyof GetRecentBlocksRecentBlocksGetResponses];

export type ExecuteRecentBlocksRecentBlocksPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/recent-blocks';
};

export type ExecuteRecentBlocksRecentBlocksPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWorldStateWorldStateGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/world-state';
};

export type GetWorldStateWorldStateGetResponses = {
    /**
     * Response Get World State World State Get
     *
     * Successful Response
     */
    200: Array<{
        [key: string]: unknown;
    }>;
};

export type GetWorldStateWorldStateGetResponse = GetWorldStateWorldStateGetResponses[keyof GetWorldStateWorldStateGetResponses];

export type GetDailyBatchDailyBatchGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Meter Ids
         *
         * Repeat param: ?meter_ids=1&meter_ids=2
         */
        meter_ids: Array<number>;
    };
    url: '/daily-batch';
};

export type GetDailyBatchDailyBatchGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDailyBatchDailyBatchGetError = GetDailyBatchDailyBatchGetErrors[keyof GetDailyBatchDailyBatchGetErrors];

export type GetDailyBatchDailyBatchGetResponses = {
    /**
     * Response Get Daily Batch Daily Batch Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetDailyBatchDailyBatchGetResponse = GetDailyBatchDailyBatchGetResponses[keyof GetDailyBatchDailyBatchGetResponses];

export type GetDailyMeterMeterIdDailyGetData = {
    body?: never;
    path: {
        /**
         * Meter Id
         */
        meter_id: number;
    };
    query?: never;
    url: '/meter/{meter_id}/daily';
};

export type GetDailyMeterMeterIdDailyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDailyMeterMeterIdDailyGetError = GetDailyMeterMeterIdDailyGetErrors[keyof GetDailyMeterMeterIdDailyGetErrors];

export type GetDailyMeterMeterIdDailyGetResponses = {
    /**
     * Response Get Daily Meter  Meter Id  Daily Get
     *
     * Successful Response
     */
    200: Array<DailyResponse>;
};

export type GetDailyMeterMeterIdDailyGetResponse = GetDailyMeterMeterIdDailyGetResponses[keyof GetDailyMeterMeterIdDailyGetResponses];

export type GetWeeklyMeterMeterIdWeeklyGetData = {
    body?: never;
    path: {
        /**
         * Meter Id
         */
        meter_id: number;
    };
    query?: never;
    url: '/meter/{meter_id}/weekly';
};

export type GetWeeklyMeterMeterIdWeeklyGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeeklyMeterMeterIdWeeklyGetError = GetWeeklyMeterMeterIdWeeklyGetErrors[keyof GetWeeklyMeterMeterIdWeeklyGetErrors];

export type GetWeeklyMeterMeterIdWeeklyGetResponses = {
    /**
     * Response Get Weekly Meter  Meter Id  Weekly Get
     *
     * Successful Response
     */
    200: Array<WeeklyResponse>;
};

export type GetWeeklyMeterMeterIdWeeklyGetResponse = GetWeeklyMeterMeterIdWeeklyGetResponses[keyof GetWeeklyMeterMeterIdWeeklyGetResponses];

export type GetWeeksOfYearMeterMeterIdWeeksYearGetData = {
    body?: never;
    path: {
        /**
         * Meter Id
         */
        meter_id: number;
        /**
         * Year
         */
        year: number;
    };
    query?: never;
    url: '/meter/{meter_id}/weeks/{year}';
};

export type GetWeeksOfYearMeterMeterIdWeeksYearGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWeeksOfYearMeterMeterIdWeeksYearGetError = GetWeeksOfYearMeterMeterIdWeeksYearGetErrors[keyof GetWeeksOfYearMeterMeterIdWeeksYearGetErrors];

export type GetWeeksOfYearMeterMeterIdWeeksYearGetResponses = {
    /**
     * Response Get Weeks Of Year Meter  Meter Id  Weeks  Year  Get
     *
     * Successful Response
     */
    200: Array<WeeksEnergyRead>;
};

export type GetWeeksOfYearMeterMeterIdWeeksYearGetResponse = GetWeeksOfYearMeterMeterIdWeeksYearGetResponses[keyof GetWeeksOfYearMeterMeterIdWeeksYearGetResponses];

export type GetMonthOfYearMeterMeterIdMonthMonthYearGetData = {
    body?: never;
    path: {
        /**
         * Meter Id
         */
        meter_id: number;
        /**
         * Year
         */
        year: number;
        /**
         * Month
         */
        month: number;
    };
    query?: never;
    url: '/meter/{meter_id}/month/{month}/{year}';
};

export type GetMonthOfYearMeterMeterIdMonthMonthYearGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetMonthOfYearMeterMeterIdMonthMonthYearGetError = GetMonthOfYearMeterMeterIdMonthMonthYearGetErrors[keyof GetMonthOfYearMeterMeterIdMonthMonthYearGetErrors];

export type GetMonthOfYearMeterMeterIdMonthMonthYearGetResponses = {
    /**
     * Response Get Month Of Year Meter  Meter Id  Month  Month   Year  Get
     *
     * Successful Response
     */
    200: Array<MonthlyEnergyRead>;
};

export type GetMonthOfYearMeterMeterIdMonthMonthYearGetResponse = GetMonthOfYearMeterMeterIdMonthMonthYearGetResponses[keyof GetMonthOfYearMeterMeterIdMonthMonthYearGetResponses];

export type GetActivitiesMeterMeterIdActivitiesGetData = {
    body?: never;
    path: {
        /**
         * Meter Id
         */
        meter_id: number;
    };
    query?: {
        /**
         * After
         */
        after?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/meter/{meter_id}/activities';
};

export type GetActivitiesMeterMeterIdActivitiesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetActivitiesMeterMeterIdActivitiesGetError = GetActivitiesMeterMeterIdActivitiesGetErrors[keyof GetActivitiesMeterMeterIdActivitiesGetErrors];

export type GetActivitiesMeterMeterIdActivitiesGetResponses = {
    /**
     * Successful Response
     */
    200: ActivitiesResponse;
};

export type GetActivitiesMeterMeterIdActivitiesGetResponse = GetActivitiesMeterMeterIdActivitiesGetResponses[keyof GetActivitiesMeterMeterIdActivitiesGetResponses];

export type GetProposalProposalTxHashGetData = {
    body?: never;
    path: {
        /**
         * Tx Hash
         */
        tx_hash: string;
    };
    query?: never;
    url: '/proposal/{tx_hash}';
};

export type GetProposalProposalTxHashGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetProposalProposalTxHashGetError = GetProposalProposalTxHashGetErrors[keyof GetProposalProposalTxHashGetErrors];

export type GetProposalProposalTxHashGetResponses = {
    /**
     * Response Get Proposal Proposal  Tx Hash  Get
     *
     * Successful Response
     */
    200: Array<ProposalsResponse>;
};

export type GetProposalProposalTxHashGetResponse = GetProposalProposalTxHashGetResponses[keyof GetProposalProposalTxHashGetResponses];
